(() => {
  'use strict';
  const DEFAULTS = {"upload":"/api/v1/tasks","status":"/api/v1/tasks/{task_id}","download":"/api/v1/tasks/{task_id}"};
  const FALLBACKS = {
    upload: ['/api/v1/tasks'],
    status: ['/api/v1/tasks/{task_id}'],
    download: ['/api/v1/tasks/{task_id}']
  };
  const $ = id => document.getElementById(id);
  const els = Object.fromEntries(['settingsToggle','settingsPanel','apiBase','uploadPath','statusPath','downloadPath','saveSettings','dropZone','videoInput','fileCard','fileName','fileSize','removeFile','taskNote','uploadButton','uploadProgress','uploadPercent','uploadBar','taskResult','createdTaskId','copyTaskId','statusTaskId','statusButton','autoPoll','statusResult','downloadTaskId','viewButton','downloadButton','downloadHint','recentTasks','clearRecent','toast'].map(id => [id, $(id)]));
  let selectedFile = null, pollTimer = null, toastTimer = null;
  const loadConfig = () => ({...DEFAULTS, ...(JSON.parse(localStorage.getItem('recon-api-config') || '{}'))});
  const saveConfig = config => localStorage.setItem('recon-api-config', JSON.stringify(config));
  const base = () => (loadConfig().base || '').replace(/\/$/, '');
  const endpoint = (path, taskId='') => base() + path.replace('{task_id}', encodeURIComponent(taskId));
  const paths = type => { const cfg=loadConfig(); return [...new Set([cfg[type], ...FALLBACKS[type]])]; };
  const formatBytes = n => n < 1024*1024 ? (n/1024).toFixed(1)+' KB' : (n/1024/1024).toFixed(1)+' MB';
  const messageFrom = data => data?.detail || data?.message || data?.error || '请求失败，请检查接口设置和 task_id。';
  const showToast = (msg, error=false) => { clearTimeout(toastTimer); els.toast.textContent=msg; els.toast.className='toast show'+(error?' error':''); toastTimer=setTimeout(()=>els.toast.className='toast',3200); };
  const requestJson = async (url, options={}) => { const res=await fetch(url,options); const type=res.headers.get('content-type')||''; const data=type.includes('json')?await res.json():await res.text(); if(!res.ok) throw Object.assign(new Error(typeof data==='string'?data:messageFrom(data)),{status:res.status}); return data; };
  const tryPaths = async (type, taskId, fn) => { let last; for(const path of paths(type)){ try{return await fn(endpoint(path,taskId),path);}catch(e){last=e;if(![404,405].includes(e.status))throw e;} } throw last||new Error('没有可用的接口'); };
  const extractTaskId = data => data?.task_id || data?.taskId || data?.id || data?.data?.task_id || data?.data?.id;
  const extractStatus = data => String(data?.status || data?.state || data?.task_status || data?.data?.status || 'unknown').toLowerCase();
  const extractProgress = data => { const v=data?.progress ?? data?.percent ?? data?.percentage ?? data?.data?.progress; return v==null?'':(Number(v)<=1?Math.round(Number(v)*100):Math.round(Number(v)))+'%'; };
  const hasRecent = id => JSON.parse(localStorage.getItem('recon-recent-tasks')||'[]').some(item=>item.id===id);
  const addRecent = (id, metadata={}) => { const saved=JSON.parse(localStorage.getItem('recon-recent-tasks')||'[]'); const index=saved.findIndex(item=>item.id===id); if(index>=0){ if(Object.keys(metadata).length){saved[index]={...saved[index],...metadata,id};localStorage.setItem('recon-recent-tasks',JSON.stringify(saved));renderRecent();} return; } const list=[{...metadata,id,time:Date.now()},...saved].slice(0,8); localStorage.setItem('recon-recent-tasks',JSON.stringify(list)); renderRecent(); };
  const removeRecent = id => { const list=JSON.parse(localStorage.getItem('recon-recent-tasks')||'[]').filter(item=>item.id!==id); localStorage.setItem('recon-recent-tasks',JSON.stringify(list)); renderRecent(); };
  const renderRecent = () => { const list=JSON.parse(localStorage.getItem('recon-recent-tasks')||'[]'); els.recentTasks.innerHTML=list.length?'':'<p class="muted">暂无最近任务</p>'; list.forEach(item=>{ const row=document.createElement('div'); row.className='recent-item'; const info=document.createElement('div'); info.style.cssText='display:flex;min-width:0;flex:1;flex-direction:column;gap:3px'; const name=document.createElement('strong'); name.textContent=item.filename||'未知视频文件'; name.title=item.filename||''; name.style.cssText='overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#e7f5ff;font-size:12px'; const note=document.createElement('span'); note.textContent=item.note||'未填写任务备注'; note.title=item.note||''; note.style.cssText='overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#91a7b9;font-size:11px'; const code=document.createElement('code'); code.textContent=item.id; code.title=item.id; code.style.cssText='display:block;flex:none;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#6e93aa;font-size:10px'; info.append(name,note,code); const actions=document.createElement('div'); actions.style.cssText='display:flex;flex:0 0 auto;align-items:center;gap:7px'; const use=document.createElement('button'); use.textContent='使用'; use.onclick=()=>{els.statusTaskId.value=item.id;els.downloadTaskId.value=item.id;queryStatus();}; const remove=document.createElement('button'); remove.type='button'; remove.textContent='删除'; remove.style.color='var(--danger)'; remove.setAttribute('aria-label','删除任务 '+item.id+' 的本地记录'); remove.onclick=()=>removeRecent(item.id); actions.append(use,remove); row.append(info,actions); els.recentTasks.append(row); }); };
  const setFile = file => { if(!file)return; if(!file.type.startsWith('video/')&&!/\.(mp4|mov|avi|mkv|webm)$/i.test(file.name)){showToast('请选择视频文件',true);return;} selectedFile=file;els.fileName.textContent=file.name;els.fileSize.textContent=formatBytes(file.size);els.fileCard.hidden=false;els.uploadButton.disabled=false;els.taskResult.hidden=true; };
  const clearFile = () => { selectedFile=null;els.videoInput.value='';els.fileCard.hidden=true;els.uploadButton.disabled=true; };
  const upload = async () => { if(!selectedFile)return; els.uploadButton.disabled=true;els.uploadProgress.hidden=false;els.taskResult.hidden=true;
    try {
      const created=await tryPaths('upload','',url=>requestJson(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:selectedFile.name,content_type:selectedFile.type||null,size:selectedFile.size})}));
      const id=extractTaskId(created), uploadUrl=created?.upload_url;
      if(!id||!uploadUrl)throw new Error('创建任务响应缺少 task_id 或 upload_url');
      await new Promise((resolve,reject)=>{const form=new FormData();form.append('file',selectedFile);const xhr=new XMLHttpRequest();xhr.open('POST',uploadUrl);xhr.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.round(e.loaded/e.total*100);els.uploadPercent.textContent=p+'%';els.uploadBar.style.width=p+'%';}};xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText)}catch{data=xhr.responseText}if(xhr.status>=200&&xhr.status<300)resolve(data);else reject(new Error(typeof data==='string'?data:messageFrom(data)));};xhr.onerror=()=>reject(new Error('视频上传失败，请检查中转节点地址和 CORS 配置'));xhr.send(form);});
      els.createdTaskId.textContent=id;els.statusTaskId.value=id;els.downloadTaskId.value=id;els.taskResult.hidden=false;addRecent(String(id),{filename:selectedFile.name,note:els.taskNote.value.trim()});showToast('视频已上传，任务创建成功');
    } catch(e) { showToast(e.message,true); }
    finally { finishUpload(); }
  };
  const finishUpload=()=>{els.uploadButton.disabled=!selectedFile;els.uploadProgress.hidden=true;els.uploadBar.style.width='0';els.uploadPercent.textContent='0%';};
  const queryStatus = async () => { const id=els.statusTaskId.value.trim(); if(!id){showToast('请输入 task_id',true);return;} const existedLocally=hasRecent(id); els.statusButton.disabled=true; try{const data=await tryPaths('status',id,url=>requestJson(url)); const status=extractStatus(data), progress=extractProgress(data); const done=/(done|complete|completed|success|succeeded|finished)/.test(status), failed=/(fail|error|cancel)/.test(status); els.statusResult.className='status-result '+(done?'done':failed?'failed':'running'); const label=done?'任务已完成':failed?'任务失败':status==='unknown'?'状态已更新':'正在处理'; const detail=data?.error_message||data?.current_stage||data?.message||'';els.statusResult.querySelector('strong').textContent=label+(progress?' · '+progress:''); els.statusResult.querySelector('p').textContent='状态：'+status+(detail?' · '+detail:''); addRecent(id,!existedLocally&&data?.original_filename?{filename:data.original_filename}:{});return data;}catch(e){els.statusResult.className='status-result failed';els.statusResult.querySelector('strong').textContent='查询失败';els.statusResult.querySelector('p').textContent=e.message;showToast(e.message,true);}finally{els.statusButton.disabled=false;} };
  const download = async () => { const id=els.downloadTaskId.value.trim(); if(!id){showToast('请输入 task_id',true);return;} const existedLocally=hasRecent(id); els.downloadButton.disabled=true;els.downloadHint.textContent='正在查询结果…'; try{const data=await tryPaths('download',id,url=>requestJson(url));addRecent(id,!existedLocally&&data?.original_filename?{filename:data.original_filename}:{});const status=extractStatus(data);if(status!=='succeeded')throw new Error('任务尚未完成，当前状态：'+status);if(!data.result_url)throw new Error('任务已完成，但接口未返回 result_url');const url=new URL(data.result_url,base()||window.location.origin).href;const a=document.createElement('a');a.href=url;a.rel='noopener';document.body.append(a);a.click();a.remove();els.downloadHint.textContent='下载已开始。';}catch(e){els.downloadHint.textContent=e.message;showToast(e.message,true);}finally{els.downloadButton.disabled=false;} };
  const viewResult = async () => { const id=els.downloadTaskId.value.trim(); if(!id){showToast('请输入 task_id',true);return;} const existedLocally=hasRecent(id); els.viewButton.disabled=true;els.downloadHint.textContent='正在检查点云结果…'; try{const data=await tryPaths('download',id,url=>requestJson(url));addRecent(id,!existedLocally&&data?.original_filename?{filename:data.original_filename}:{});const status=extractStatus(data);if(status!=='succeeded')throw new Error('任务尚未完成，当前状态：'+status);if(!data.result_url)throw new Error('任务已完成，但接口未返回 result_url');if(!window.pointCloudViewer)throw new Error('点云查看器尚未加载完成，请刷新页面后重试');const resultUrl=new URL(data.result_url,base()||window.location.origin).href;window.pointCloudViewer.open({taskId:id,resultUrl});els.downloadHint.textContent='已在页面底部打开点云结果。';}catch(e){els.downloadHint.textContent=e.message;showToast(e.message,true);}finally{els.viewButton.disabled=false;} };
  const cfg=loadConfig();els.apiBase.value=cfg.base||'';els.uploadPath.value=cfg.upload;els.statusPath.value=cfg.status;els.downloadPath.value=cfg.download;
  els.settingsToggle.onclick=()=>els.settingsPanel.hidden=!els.settingsPanel.hidden;
  els.saveSettings.onclick=()=>{saveConfig({base:els.apiBase.value.trim(),upload:els.uploadPath.value.trim()||DEFAULTS.upload,status:els.statusPath.value.trim()||DEFAULTS.status,download:els.downloadPath.value.trim()||DEFAULTS.download});showToast('接口设置已保存');els.settingsPanel.hidden=true;};
  els.dropZone.ondragover=e=>{e.preventDefault();els.dropZone.classList.add('dragging');};els.dropZone.ondragleave=()=>els.dropZone.classList.remove('dragging');els.dropZone.ondrop=e=>{e.preventDefault();els.dropZone.classList.remove('dragging');setFile(e.dataTransfer.files[0]);};els.dropZone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.videoInput.click();}};
  els.videoInput.onchange=e=>setFile(e.target.files[0]);els.removeFile.onclick=e=>{e.preventDefault();clearFile();};els.uploadButton.onclick=upload;els.copyTaskId.onclick=async()=>{await navigator.clipboard.writeText(els.createdTaskId.textContent);showToast('task_id 已复制');};els.statusButton.onclick=queryStatus;els.statusTaskId.onkeydown=e=>{if(e.key==='Enter')queryStatus();};els.autoPoll.onchange=()=>{clearInterval(pollTimer);if(els.autoPoll.checked){queryStatus();pollTimer=setInterval(queryStatus,3000);}};els.viewButton.onclick=viewResult;els.downloadButton.onclick=download;els.downloadTaskId.onkeydown=e=>{if(e.key==='Enter')download();};els.clearRecent.onclick=()=>{localStorage.removeItem('recon-recent-tasks');renderRecent();};renderRecent();
})();
